### ISSUE TITLE
Fix date format in tagged page list

### ISSUE THREAD

**Issue by pariksheet** [abhijeetdhumal/techovercoffee#3]
https://backtracking.dev/tags/kafka
<img width="1040" alt="Screen Shot 2020-08-31 at 8 44 28 PM" src="https://user-images.githubusercontent.com/1144685/91755081-d18fba00-ebca-11ea-9141-0bb50bf21131.png">

**Comment by abhijeetdhumal** [comment]
Fixed the issue and now the date format is available in proper format.
